### ISSUE TITLE
Type issues when using null driver

### ISSUE THREAD

**Issue by westinsykes** [TriadSemi/triad_openvr#20]
I have a system which is setup to not have the HMD connected by following this tutorial: http://help.triadsemi.com/en/articles/836917-steamvr-tracking-without-an-hmd

What I have found is that the getStringTrackedDeviceProperty function used by vr_tracked_device.get_model and vr_tracked_device.get_serial now return strings rather than bytes objects causing an exception when it calls the decode method. It would be simple just check the type in all functions that use that and decode if necessary, but it seemed odd to me that it would be returning various types at all.

**Comment by westinsykes** [comment]
After more investigation, I think this issue is an incompatibility with the latest pyopenvr.

**Comment by lgbeno** [comment]
Thanks for investigating this!  Glad to see that you are using this, reporting issues and most importantly finding solutions!
