### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by hardway777** [TriadSemi/triad_openvr#30]
Found 2 Tracking References
  tracking_reference_1 (LHB-AED900E5, Mode HTC V2-XD/XE, HTC V2-XD/XE)
  tracking_reference_2 (LHB-98BC63FA, Mode HTC V2-XD/XE, HTC V2-XD/XE)
Found 1 HMD
  hmd_1 (LHR-13D8CFA7, Vive. MV)
Found 2 Controllers
  controller_1 (LHR-FF2B1D44, Vive. Controller MV)
  controller_2 (LHR-FFDEDF40, Vive. Controller MV)
Found 0 Trackers
Traceback (most recent call last):
  File "E:\Tools\triad_openvr-master\controller_test.py", line 20, in <module>
    for each in v.devices["controller_1"].get_pose_euler():
TypeError: 'NoneType' object is not iterable

**Comment by ZXP-S-works** [comment]
I encountered the same issue. I solved the problem by moving the controller within tracker's view. The STEAMVR should display both controller and the base station, see pic:
![image](https://github.com/TriadSemi/triad_openvr/assets/42163887/74cb6c84-83fa-4cc2-b66d-7f941671c8ed)
