### ISSUE TITLE
update frequency

### ISSUE THREAD

**Issue by chaolmu** [TriadSemi/triad_openvr#6]
Since the lighthouse works at frequency of 60Hz, why does "tracker_test" update pose information at 250Hz?

**Comment by kyranf** [comment]
I don't have any authority here, but the 250Hz is the update rate of the IMU sensor which you get the full stream of data from.  You can generate pose updates at 250Hz with that info, and do corrections at 60Hz

**Comment by lgbeno** [comment]
@kyranf is exactly correct, SteamVR updates pose at a rate of 250Hz and then the optical system "dead reckons" drift at the slower optical rate.  Doc-ok does a good job of explaining here: http://doc-ok.org/?p=1478
